// <auto-generated />
namespace ABC_University.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class addlocationcolum : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addlocationcolum));
        
        string IMigrationMetadata.Id
        {
            get { return "202508291059220_add-location-colum"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
